apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: general-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Petrichao/otus_project.git
    targetRevision: HEAD
    path: manifests/general
  destination:
    server: https://kubernetes.default.svc
    namespace: otus-proj
  syncPolicy:
    automated:
      selfHeal: true
      prune: true